name: Cypress UI Automation
on:
  push:
    branches: [ master ]
  pull_request:

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: cypress-ui-automation
          install-command: npm install
          runTests: npm cy:run
